### ISSUE TITLE
Question about the anemometer wind speed calculation

### ISSUE THREAD

**Issue by macadev** [sparkfun/SparkFun_Weather_Meter_Kit_Arduino_Library#6]
Hi! Thanks for this wonderful library. Having a ton of fun playing with these sensors.

I'm curious about one thing regarding the anemometer wind speed calculation - why did you choose to trigger the windspeed interrupt on CHANGE instead of just on RISING?

I get that CHANGE will trigger the interrupt when the Voltage goes high and then when it goes low, and that the getWindSpeed() function correctly accounts for this as illustrated in this great comment:

```
// Convert milliseconds to seconds, and counts per second to kph. Need to
// divide by 2 to account for using both rising and falling edges
windSpeed *= 1000 * _calibrationParams.kphPerCountPerSec / 2;
```

But wouldn't the wind speed calculations be more precise if the interrupt is only triggered on RISING? Why did you decide to trigger it on CHANGE?

The spec sheet for the anemometer says that a speed of 2.4 km/h results in the switch closing once a second. I interpret 'closes' as suggesting "interrupt when voltage goes high".

Thanks for your time in helping clarify this!

**Comment by macadev** [comment]
As a follow up question... are you using a 10pF capacitor to debounce the anemometer as suggested by data sheet? Or are you following a different approach for debouncing?

**Comment by macadev** [comment]
@sfe-SparkFro, thank you so much for the extremely detailed answer! It's so helpful.

I was having trouble calibrating the anemometer, and now I think it's because I was using a capacitor that is just too small for the switch debounce to work correctly. I'll test calibrating with an RC time constant of ~4.3 ms as the micromod weather board does.

**Comment by zavinator** [comment]
Hi! I did a quick sanity check on the anemometer behaviour.

Using an oscilloscope and a desk fan, I measured approximately 5 Hz at the anemometer output, which corresponds to roughly 12 km/h.

**What worked best for me:**
- Add a 100 nF capacitor to GND at the signal line, internal ESP pull up (~40k)
- Since the reed switch’s pulse width isn’t constant (it is asymmetric), count only the RISING edge.
- Apply a short software debounce (I used 1 ms) to filter out contact chatter. Without it, I still observed false (too high) counts. 
- Use a 10-second accumulation window for smoother and more stable wind-speed averaging.

I noticed you’re using both the MCU’s internal pull-up and an external pull-up resistor in the schematic.
It’s better to choose one or the other — either rely on the internal pull-up or use an external one, but not both in parallel.
(Or are R16 + R14 meant to represent the internal pull-ups?)

**For context: I’m using a standard ESP32 + anemometer, not the SparkFun board.**
