### ISSUE TITLE
Speed calibration

### ISSUE THREAD

**Issue by chelliwell** [sparkfun/SparkFun_Weather_Meter_Kit_Arduino_Library#7]
Hi, I noticed you've got some apps for calibration of wind speed. 
I was wondering if you found these to be often necessary? e.g. Does one Meter Kit anenometer tend to differ a bit from another for speed vs. pulses? And/or is the 'pulses per mph' non-linear over a range of wind speed? Thanks.

**Comment by sfe-SparkFro** [comment]
Hi there, apologies for the delay in response!

I have personally only tested a single Weather Meter Kit. This library uses the values from the datasheet as the default calibration values in the library, which I then tested to verify that the values were in the right ballpark as a sanity check. I did not test multiple Weather Meter Kits to compare accuracy between them, nor did I do any linearity analysis or anything like that. I suspect you may find some minor variation between units with the anemometer and rainfall counter, but the calibration values are there for you to tune if desired. I suspect there may be some non-linearity with those 2 sensors as well, but compensating for that was deemed to be more effort than it's worth (though you're always welcome to open a pull request if you come up with a good solution!).

I'm going to close this since it's more of a question than an issue, but please feel free to open a new issue if you do find a true problem! Thanks!
